title: GrainForge
description: The documentation and manual for GrainForge - the Mac App for digitalizing film
theme: just-the-docs

url: https://docs.grainforge.de

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
